apiVersion: v1
kind: Secret
metadata:
  name: api-secret # The name you will reference in your Deployment
type: Opaque # Default type for generic passwords
data:
  # Keys (USERNAME/PASSWORD) must be plain text. Values must be Base64 encoded strings.
  DB_USERNAME: ZGJ1c2Vy                # 'dbuser'
  DB_PASSWORD: U3Ryb25nUGFzc3dvcmQxMjMh # 'StrongPassword123!'
