apiVersion: v1
kind: Secret
metadata:
  name: api-secret # The name you will reference in your Deployment
type: Opaque # Default type for generic passwords
data:
  #Values must be Base64 encoded strings.
  # Database
  POSTGRES_USER: ZGV2dXNlcg==  #"devuser"
  POSTGRES_PASSWORD: ZGV2cGFzcw== #"devpass"
