apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-app # Matches the label in your Deployment YAML
  type: NodePort # Makes the service accessible from outside the cluster locally
  ports:
    - protocol: TCP
      port: 80 # The port the service itself exposes internally
      targetPort: 3000 # The containerPort defined in the Deployment/ application exposed port
      nodePort: 31000 # External access port