apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
spec:
  accessModes:
    # ReadWriteOnce means it can be mounted as read-write by a single Node.
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Request 5 Gigabytes of storage
