apiVersion: v1
kind: Service
metadata:
  name: postgres-service # This is the internal DNS name you use in your Express app
spec:
  selector:
    app: postgres-deployment # Matches the labels on the Deployment Pods
  ports:
    - protocol: TCP
      port: 5432 # Service port
      targetPort: 5432 # Container port
      nodePort: 31543
  type: ClusterIP # Makes it accessible only within the cluster
#  type: NodePort # Makes it accessible outside the cluster
