apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres-deployment
spec:
  replicas: 1 # Start with 1 replica for a standard setup
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      labels:
        app: postgres-deployment
    spec:
      containers:
        - name: postgres
          image: postgres:14 # Use a specific, stable version of the Postgres image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432 # Default Postgres port
          envFrom:
            # Loads all key-value pairs from the Secret defined in Step 1
            - secretRef:
                name: postgres-secret
          volumeMounts:
            # Mount the volume claim inside the container at the default Postgres data path
            - mountPath: "/var/lib/postgresql/data"
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
