apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData: # Use 'stringData' to input human-readable values; K8s handles the encoding
  POSTGRES_USER: "devuser"
  POSTGRES_PASSWORD: "devpass"
  POSTGRES_DB: "devdb"
